### PR TITLE
The extracted articles for indexing

### PR DESCRIPTION
**Pull request by ovoistinov**

### CODE REVIEW

**Comment by gezhao** [comment]
Questions:
1. the name convention is for the article linking to the url in the original excel doc? What is the original excel doc stored
2. Why two folders storing articles.

Also a minor suggestion:
Can we have a short description for the changes made in the PR and the quick design summary (e.g. folder structure and the reason behind it) for easier review?

**Comment by XingfeiYu** [comment]
Great, I guess you extracted these content from web page, right? We are going to index these content for search only, if users are interested in it and want to know more, there should be an original URL link, so can we have the original link in the file?

**Comment by ovoistinov** [comment]
@gezhao the naming convention is ROW_NUMER-AUTHOR_NAME-ARTICLE_NAME.txt. The second directory is not needed, good catch. Will add readme with some design and usage details.

@XingfeiYu Thanks for the nice point. I will append the original link to the end of the file like "More info: URL"

**Comment by ovoistinov** [comment]
Re-generated the articles including the original link this time. All the other suggestions are added to PR #13 . Ready for another review.

**Comment by gezhao** [comment]
I am OK with the changes...Xingfei please do a final review and see if "original link" approach is working for you. If so, merge and close the issue and move on. Thanks all.

**Comment by XingfeiYu** [comment]
Looks good for me,  thanks!

**Pull request merged**
